"""変更内容の説明

Revision ID: 75cadcbcfeb8
Revises: 001
Create Date: 2025-09-24 04:19:47.022294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cadcbcfeb8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_created_at', table_name='contacts')
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_index('ix_contacts_lesson_type', table_name='contacts')
    op.drop_index('ix_contacts_status', table_name='contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_status', 'contacts', ['status'], unique=False)
    op.create_index('ix_contacts_lesson_type', 'contacts', ['lesson_type'], unique=False)
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('ix_contacts_created_at', 'contacts', ['created_at'], unique=False)
    # ### end Alembic commands ###